# This workflow will install Python dependencies and run builddocs.py to build HTML docs using Sphinx.

name: Build HTML Docs

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]
  workflow_dispatch:
  # Workflow can also be triggered manually (will build latest docs)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pip and Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install -U sphinx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run builddocs script
        run: |
          if ${GITHUB_REF}; then
            python docsrc/builddocs.py --output ../docs --version ${GITHUB_REF}
          else
            python docsrc/builddocs.py --output ../docs
          fi
