# This workflow will install Python dependencies and run builddocs.py to build HTML docs using Sphinx.

name: Build HTML Docs

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    # Workflow can also be triggered manually
    inputs:
      version:
        description: 'Doc version(s) to build (latest, all, stable, <tag>)'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pip and Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install -U sphinx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run builddocs script
        run: |
          if [[ ! -z "${INPUT_VERSION}" ]]; then
            python docs/builddocs.py --version ${INPUT_VERSION}
          else
            python docs/builddocs.py
          fi
      - name: Commit documentation changes
        run: |
          git clone https://github.com/GeoCat/qgis-bridge-plugin.git --branch gh-pages --single-branch gh-pages
          cp -r build/docs/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # Above command will fail if there are no changes: ignore return code
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}